export const COLOR = {
  SET_SELECTED: 'SET_SELECTED_COLOR',
  SET_FILTERED: 'SET_FILTERED_COLOR',
  REMOVE_FILTERED: 'REMOVE_FILTERED_COLOR'
}

export const WORDS = {
  ADD_WORD: 'ADD_WORD_TO_LIST',
  REMOVE_WORD: 'REMOVE_WORD_FROM_LIST'
}